[package]
name = "prepona"
version = "0.1.0"
authors = ["m.amin.rayej <m.amin.rayej@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "A graph crate with simplicity in mind"
repository = "https://github.com/maminrayej/prepona"
homepage = "https://github.com/maminrayej/prepona"
documentation = "https://docs.rs/prepona"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
magnitude = "0.3.2"
anyhow = "1.0.36"